# Generated by Django 4.1.2 on 2022-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(default='code', max_length=5),
            preserve_default=False,
        ),
    ]
