# Generated by Django 4.1.2 on 2022-11-03 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_weeklysale_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklysale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weeklysale',
            name='shop',
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='cost_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='price_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='units_bought',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='units_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='units_wastage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyShopSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('upload', models.CharField(blank=True, max_length=20, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead', models.CharField(choices=[('Personnel cost', 'personnel cost'), ('Premises cost', 'premises cost'), ('Other overheads', 'other overheads')], max_length=30)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('shop_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.weeklyshopsummary')),
            ],
        ),
        migrations.AddField(
            model_name='weeklysale',
            name='shop_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.weeklyshopsummary'),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.fruit'),
        ),
    ]
