# Generated by Django 4.1.2 on 2022-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_fruit_remove_weeklysale_date_remove_weeklysale_shop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyoverhead',
            old_name='shop_date',
            new_name='weekly_shop_summary',
        ),
        migrations.RenameField(
            model_name='weeklysale',
            old_name='shop_date',
            new_name='weekly_shop_summary',
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysale',
            name='price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
