# Generated by Django 4.1.2 on 2022-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_shop_date_weeklyoverhead_weekly_shop_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyoverhead',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyshopsummary',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='data/uploads/'),
        ),
    ]
