# Generated by Django 4.1.2 on 2022-11-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_weeklyoverhead_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyshopsummary',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='weeklyshopsummary',
            name='upload',
            field=models.FileField(upload_to='data/uploads/'),
        ),
    ]
