# Generated by Django 4.1.2 on 2022-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_weeklyshopsummary_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyshopsummary',
            name='upload',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
